### ISSUE TITLE
Data download problem

### ISSUE THREAD

**Issue by leonardomarino** [cdeboever3/deboever-sf3b1-2015#1]
Hi @cdeboever3 I just installed all the prerequisites and when trying to download the data I get this error:

$ ipython ext_data.ipynb --pylab inline
WARNING: 'inline' not available as pylab backend, using 'auto' instead.
## Using matplotlib backend: Qt4Agg

NameError                                 Traceback (most recent call last)
/home/marino/projects/deboever-sf3b1-2015/notebooks/ext_data.ipynb in <module>()
     26     {
     27      "cell_type": "code",
---> 28      "collapsed": false,
     29      "input": [
     30       "import os\n",

NameError: name 'false' is not defined

$ ipython figshare_download.ipynb --pylab inline
WARNING: 'inline' not available as pylab backend, using 'auto' instead.
## Using matplotlib backend: Qt4Agg

NameError                                 Traceback (most recent call last)
/home/marino/projects/deboever-sf3b1-2015/notebooks/figshare_download.ipynb in <module>()
     26     {
     27      "cell_type": "code",
---> 28      "collapsed": false,
     29      "input": [
     30       "import os\n",

NameError: name 'false' is not defined

Please advise, I am not sure if I am running the commands correctly.

**Comment by cdeboever3** [comment]
Hi @leonardomarino, have you set up an IPython notebook environment before? You'll want to change into the notebooks directory and run `ipython notebook --pylab inline` to start the notebook server (it should open automatically in a web browser). Then you can open the ext_data.ipynb notebook and run it.

**Comment by leonardomarino** [comment]
Unfortunately, I am new to them. I just tried to run ipython notebook --pylab inline and I am getting this message:

$ ipython notebook --pylab inline
[E 12:59:02.633 NotebookApp] Support for specifying --pylab on the command line has been removed.
[E 12:59:02.633 NotebookApp] Please use `%pylab inline` or `%matplotlib inline` in the notebook itself.
[marino@marino-johnson:~/projects/deboever-sf3b1-2015/notebooks]$

**Comment by cdeboever3** [comment]
I pushed an update that should remove the need to use the `--pylab inline` flag which apparently has been removed for current versions of IPython. So pull the latest version of the repo and try starting the notebook with just `ipython notebook`.

**Comment by leonardomarino** [comment]
Great! Now I am able to see a browser window and a set of files that can be run. Looks pretty cool.

I am trying to run the figshare_download notebook and I am getting this:

Downloading: 1120663.zip Bytes: 4326983798

---

NameError                                 Traceback (most recent call last)
<ipython-input-2-1aa29ff3e68d> in <module>()
      7 file_size = int(meta.getheaders("Content-Length")[0])
      8 print("Downloading: %s Bytes: %s" % (file_name, file_size))
----> 9 sys.stdout.flush()
     10 
     11 file_size_dl = 0

NameError: name 'sys' is not defined

**Comment by cdeboever3** [comment]
Alright I fixed that one, try pulling the latest changes in. Thanks for your patience as we get this going, you're the first external person to grab the data so this is a big help in getting this usable for others. Also, as you may have seen, github now renders the notebooks natively so you can render any of the notebooks directly on github if that's useful at any point.

**Comment by leonardomarino** [comment]
Yes, that is definitely useful. I was able to run a notebook "manually" by executing the code in an interactive python session after downloading the data and placing in it in the expected locations. So thanks so much. I was wondering what kind of preprocessing steps do I need if I have bam data so I can compare it with your data and the Ferreira data as described in ferreira_comparison. Could you provide me with the steps from bam to the python structures that you have created so I can do a comparison of data from other sources?

**Comment by cdeboever3** [comment]
Great, it sounds like we've fixed the issue so I'll close this. One way to compare to my data and the Ferreira data is to obtain splice junction coverage from your data. You could count the coverage yourself from your bam files using bedtools or something. You could also use STAR to realign your data since the SJ.out.tab that STAR creates has the junction coverages. If you have some splice junctions that you think are differentially spliced, you can compare to the coordinates as I do in the Ferreira comparison notebook. I guess it just depends on what exactly you have and want to compare.
