### ISSUE TITLE
Upstream analysis issue

### ISSUE THREAD

**Issue by ebonner303** [cdeboever3/deboever-sf3b1-2015#3]
If this isn't allowed then please ignore. I am trying to recapitulate your analysis using STAR. I pulled the junctions_info.tsv off figshare thinking that it is the splice junction database used for the splice junction analysis in STAR, but my SJ.out.tab results are strange (almost all reads are in multi-map). Did I pull the wrong document?  I am sorry if this isn't relevant to this forum. I am new to bioinformatics and trying to teach myself this analysis. Any advice would be greatly appreciated.

**Comment by cdeboever3** [comment]
Hi @ebonner303, are you trying to run STAR on your own RNA-seq data? I honestly don't quite remember which file I gave to STAR to define the junctions, but I think junctions_info.tsv probably contains the junctions that I gave to STAR. One thing to be careful about is that these junctions are in hg19, so they won't work if you are trying to align to GRCh38. If you are trying to align your own RNA-seq data and getting a lot of multi-mapping, I suppose there could be several reasons for that. I'd try to visualize some of the multi-mapping reads in IGV or on the UCSC Genome Browser. https://www.biostars.org/ is a good place to go if you have general bioinformatics questions.

**Comment by ebonner303** [comment]
Hi @cdeboever3, I am running this analysis on some published data.  I am using GRCh38. Hopefully this explains my funky results. I am going to try and re-run this with the genome corresponding to your file. Thank you so much for your help!

**Comment by cdeboever3** [comment]
Sounds good, that should help. I'll close this for now but feel free to reopen if needed.
